### ISSUE TITLE
Multiple languages

### ISSUE THREAD

**Issue by 3Samourai** [GDQuest/godot-tours#25]
**I'm submitting a...**

- [ ] Bug report.
- [x] Feature request.

## Bug report ##

**What is the current behavior?**

**What is the expected behavior?**

**Tell us the steps to reproduce the bug, and if possible share a minimal demo of the problem.** 

## Feature request ##

By providing documentation in multiple languages, we ensures that developers from diverse linguistic backgrounds can easily grasp the intricacies of the engine, thereby democratizing access to game development knowledge. This approach not only encourages a more global and collaborative community but also facilitates the exchange of ideas and solutions among developers who may not be proficient in English. Ultimately, embracing translation enhances the user experience, promotes learning, and strengthens Godot's position as a versatile and user-friendly game development platform for creators around the globe.

**Tell us which solutions you've explored, the solution you would pick, and why you think it would be the best for everyone.**
N/A
## Other ##

**Other information**

**Comment by NathanLovato** [comment]
The framework already supports translation, as mentioned in the README, if that's what you're asking about.

If you'd like to request translations for a specific tour, like https://github.com/gdquest-demos/godot-tours-101-the-godot-editor, we'd love to have that, but we don't have the resources to set up a translation pipeline right now.

We've laid the foundations by coding translation support in the tour framework, then for now we would need a developer willing to contribute the next piece of the puzzle (build system, crowdsourced translation workflow that can be reused by anyone making a tour in the community). That, or a company to sponsor such a developer.

**Comment by NathanLovato** [comment]
Okay, then I'll close this and open an issue dedicated to this topic for clarity.
