### ISSUE TITLE
Godot tours 101 does not advance after clicking play button

### ISSUE THREAD

**Issue by cmbernard333** [GDQuest/godot-tours#4]
**I'm submitting a...**

- [X] Bug report.
- [ ] Feature request.

## Bug report ##

**What is the current behavior?**

Clicking the play button in the Godot Tours 101 app does not cause the checkbox to fill so there is no way to advance to the second step.

**What is the expected behavior?**

Clicking the play button in the Godot Tours 101 fills the checkbox so the second slide can be advanced to.

**Tell us the steps to reproduce the bug, and if possible share a minimal demo of the problem.** 

1. Load Godot Tours 101 in Godot Editor 4.2.1
2. Advance to the "Try the Game" step.
3. Click the play button to start the game.
4. Play the game.
5. Close the game with F8 or close button.
6. The checkbox to advance to the second step does not highlight.

## Feature request ##

**Describe the problem you're trying to solve.**

**Tell us which solutions you've explored, the solution you would pick, and why you think it would be the best for everyone.**

## Other ##

**Other information** 

- Windows 11 Pro 64 bit
- Godot Editor 4.2.1
- Version 1.0.0 of Godot Tours project.
- Godot Engine v4.2.1.stable.mono.official.b09f793f5 - https://godotengine.org
- Vulkan API 1.3.260 - Forward Mobile - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 4070

https://github.com/GDQuest/godot-tours/assets/4392507/a0cd6d12-efec-4b7e-939f-840affd32858

**Comment by NathanLovato** [comment]
You need the standard edition of Godot to run Godot tours. It doesn't work with the .NET edition. We mention this on both repositories and on our website below the 101 tour's download button:

![image](https://github.com/GDQuest/godot-tours/assets/12694995/af26a3a2-fabd-488b-b2ad-68f9f26da242)

**Comment by cmbernard333** [comment]
Thank you for the quick response. Is there a reason for that? I’m new to godot, but not new to C#. Trying to get a lay of the land.

**Comment by OmnesPotens** [comment]
@NathanLovato I believe this still works with the .NET version of Godot on 4.2.1 with some modification. See this issue: https://github.com/gdquest-demos/godot-tours-101-the-godot-editor/issues/4
