### ISSUE TITLE
Project crash with "Cannot call method 'get_children' on a null value" error

### ISSUE THREAD

**Issue by oquevillart** [GDQuest/godot-tours#7]
**I'm submitting a...**

- [x] Bug report.
- [ ] Feature request.

## Bug report ##

**What is the current behavior?**
When i start the project, the project is crashing.

**What is the expected behavior?**
the project dosent crash on start

**Tell us the steps to reproduce the bug, and if possible share a minimal demo of the problem.** 

1. Launch godot
2. start the project

## Other ##

**Other information** 
My Computer configuration in case that can help : 
ram : 32Go
processor : AMD Ryzen 5 5600X 6-Core 
CG : GTX 1060 6Go

my nvidia driver is up to date but in case that can help : Geforce Game Ready Driver Version 546.33

my godot version : 4.2.1

![BUG](https://github.com/GDQuest/godot-tours/assets/105644850/3b3caa73-cb35-4734-8303-afd998b64942)

**Comment by NathanLovato** [comment]
Have you tried opening other Godot projects? Can you open projects using the Compatibility rendering backend without any issues? Have you tried restarting your computer? The error and the screenshot look like a GPU/driver compatibility problem, it may not be related to this addon.

**Comment by oquevillart** [comment]
Thank you for your help and the hard work . I have restart my computer and it work like a charm...
i don't know why  i havent do this... Habitually it's me that say to other people to restart there computer ! What a developper ! I'm sorry

**Comment by NathanLovato** [comment]
No worries, it happens to all of us!
